"""Regenerate lib/excuse_consensus.py from the contract.

    python scripts/lift.py

The lifted module claims to be the ruling rules "as the contract
runs them". Maintaining it by hand makes that claim false the first time
somebody edits one side, so it is generated, and
tests/test_logic.py::TestLibExcuse compares the two parsed trees function by
function. scripts/mutate.py runs this inside every mutated copy, so the excuse
test can never stand in for the behavioural test a mutation deserves.
"""

import ast
import pathlib

ROOT = pathlib.Path(__file__).absolute().parent.parent
CONTRACT = ROOT / "excuse.py"
OUT = ROOT / "lib" / "excuse_consensus.py"

CONSTANTS = [
    "NONE", "MAX_REASON",
]

FUNCTIONS = [
    "clean_text", "split_list", "parse_days", "normalise_choice", "unreverse", "fold",
    "ruling_sound", "excuse_agrees", "sanitise_reason", "fence", "build_prompt",
]

HEADER = '''# excuse_consensus.py - the ruling rules, lifted out to be copied.
#
# GENERATED by scripts/lift.py from excuse.py. Do not edit by hand:
# tests/test_logic.py compares the two parsed trees function by function.
#
# GenLayer contracts run as ONE Python file inside the GenVM. There is no
# cross-file import at deploy time, so this is not a module a contract imports:
# it is a curated block, for reading and lifting into another project without
# reading a whole contract first.
#
# Everything here is pure. No storage, no network, no model.
#
# The ideas worth lifting: the answer that crosses consensus is an index into
# a list the contract already holds, or none (normalise_choice, ruling_sound);
# unreverse() and fold() read the second presentation order back and turn any
# disagreement into none, because an excuse has to be clear to move a deadline.

'''


def main():
    src = CONTRACT.read_text(encoding="utf-8")
    tree = ast.parse(src)
    lines = src.splitlines(keepends=True)

    def segment(node, with_comments=False):
        start = node.lineno - 1
        while with_comments and start > 0 and lines[start - 1].startswith("#"):
            start -= 1
        return "".join(lines[start:node.end_lineno]).rstrip("\n")

    parts = []
    for name in CONSTANTS:
        for n in tree.body:
            if isinstance(n, ast.Assign) and any(isinstance(t, ast.Name) and t.id == name for t in n.targets):
                parts.append(segment(n))
                break
        else:
            raise SystemExit(f"the contract no longer defines {name}")

    fns = []
    for name in FUNCTIONS:
        for n in tree.body:
            if isinstance(n, ast.FunctionDef) and n.name == name:
                fns.append(segment(n, with_comments=True))
                break
        else:
            raise SystemExit(f"the contract no longer defines {name}()")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEADER + "\n".join(parts) + "\n\n\n" + "\n\n\n".join(fns) + "\n",
                   encoding="utf-8", newline="\n")
    print(f"  {OUT.relative_to(ROOT).as_posix()}: {len(CONSTANTS)} constants, {len(FUNCTIONS)} functions")


if __name__ == "__main__":
    main()
